sudo: required

language: python
python:
  - "3.6"

services:
  - docker

before_install:
  - ./scripts/setup-protoc-docker.sh

before_script:
  - ./scripts/run_builder_task.sh cargo-fmt --all-check

script:
  - ./scripts/run_tests.sh
  - docker-compose up grpc_rs_client
  - docker-compose up tower_grpc_client
