sudo: required

language: python
python:
  - "3.6"

services:
  - docker

before_install:
  - ./scripts/setup-protoc-docker.sh

script:
  - ./scripts/run_tests.sh
  - docker-compose run --rm grpc_client
