[package]
name = "grpc-rs-server"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
grpc-rs-gen = { path = "../grpc-rs-gen" }
grpcio = "0.4.*"
log = "*"
env_logger = "*"
futures = "0.1.*"
